version: "3.6"

services:
  traefik:
    image: traefik:1.7
    command:
      - --docker.exposedbydefault=false
      - --api
      - --docker
      - --docker.swarmMode
      - --docker.domain=proxy
      - --docker.watch
      - --logLevel=ERROR
      - --entrypoints=Name:http Address::80 # Redirect.EntryPoint:https
      - --entrypoints=Name:https Address::443 ## TLS:/run/secrets/tls.cert,/run/secrets/tls.key
      - --defaultentrypoints=http,https
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    # secrets:
    #   - tls.cert
    #   - tls.key
    networks:
      - proxy
    ports:
      - 80:80
      - 8080:8080
      - 443:443
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure

networks:
  proxy:
    driver: overlay
    external: true
    
# secrets:
#   tls.cert:
#     external: true
#   tls.key:
#     external: true
